// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj817S_VZvlW0izcLXrSenBt5zekV1Mco',
    appId: '1:648950609561:web:b88867d1933e6d94b1aa08',
    messagingSenderId: '648950609561',
    projectId: 'eduon-a2ec6',
    authDomain: 'eduon-a2ec6.firebaseapp.com',
    storageBucket: 'eduon-a2ec6.firebasestorage.app',
    measurementId: 'G-9X5BR85J03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0uVjoHPpTR3HxkETDZz0Bv-Veylz7j5U',
    appId: '1:648950609561:android:6b35e89be7c1598db1aa08',
    messagingSenderId: '648950609561',
    projectId: 'eduon-a2ec6',
    storageBucket: 'eduon-a2ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUchkQgLPg88QoxKDAP9Ysxj-7UdrQR8',
    appId: '1:648950609561:ios:4506146c75ff8841b1aa08',
    messagingSenderId: '648950609561',
    projectId: 'eduon-a2ec6',
    storageBucket: 'eduon-a2ec6.firebasestorage.app',
    iosBundleId: 'com.example.eduon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUchkQgLPg88QoxKDAP9Ysxj-7UdrQR8',
    appId: '1:648950609561:ios:4506146c75ff8841b1aa08',
    messagingSenderId: '648950609561',
    projectId: 'eduon-a2ec6',
    storageBucket: 'eduon-a2ec6.firebasestorage.app',
    iosBundleId: 'com.example.eduon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj817S_VZvlW0izcLXrSenBt5zekV1Mco',
    appId: '1:648950609561:web:1f289cd54618e53bb1aa08',
    messagingSenderId: '648950609561',
    projectId: 'eduon-a2ec6',
    authDomain: 'eduon-a2ec6.firebaseapp.com',
    storageBucket: 'eduon-a2ec6.firebasestorage.app',
    measurementId: 'G-24GE7THY1C',
  );

}